server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Healthcheck
  location = /health {
    access_log off;
    return 200 "ok\n";
  }

  # Cache de assets estáticos
  location ~* \.(?:js|css|woff2?|svg|png|jpg|webp)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
